### ISSUE TITLE
log is not defined  Fails on nodejs v4.1.0  ... yet OK on v4.0.0

### ISSUE THREAD

**Issue by scottstensland** [indexzero/http-server#178]
this error only happens on nodejs  v4.1.0     works fine on any previous node like v4.0.0

http-server

 through https
/home/scott/node-v4.1.0/lib/node_modules/http-server/bin/http-server:118
    log('\nAvailable on:'.yellow);
    ^

ReferenceError: log is not defined
    at Server.<anonymous> (/home/scott/node-v4.1.0/lib/node_modules/http-server/bin/http-server:118:5)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1257:10)
    at doNTCallback1 (node.js:418:9)
    at process._tickCallback (node.js:340:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3

installed just now using 

npm install -g http-server

as per its package.json   

  "name": "http-server",
  "version": "0.8.2",

node --version
v4.1.0

ubuntu 15.04

**Comment by impleri** [comment]
I'm getting it on 0.12.x and 0.10.x as well. Could it be a change in the dependency chain

**Comment by impleri** [comment]
Nope. It's https://github.com/indexzero/http-server/commit/352ee1c23c35f36c5d1163b216f18d4548d48fa7 which renames the log function to logger.

**Comment by indexzero** [comment]
This was fixed. Please update.

**Comment by scottstensland** [comment]
sweet - all ship shape - keep up the good work

cheers
