### ISSUE TITLE
shell broken after http-server few start/stop

### ISSUE THREAD

**Issue by bskydive** [indexzero/http-server#290]
OS: OpenSuSe Linux 42.1 (x86_64) kernel 4.1.26-21
npm: 3.10.3
nodejs: 4.4.5
http-server: 0.9.0

```

# http-server -c -1 -P http://somesite:8086 --cors
path.js:424
    var path = (i >= 0) ? arguments[i] : process.cwd();
                                                 ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at Function.Module._resolveLookupPaths (module.js:249:17)
    at Function.Module._resolveFilename (module.js:316:31)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/http-server/bin/http-server:7:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

```

# bash
... getcwd: cannot access parent directories ...

```

**Comment by bskydive** [comment]
according to:
http://stackoverflow.com/questions/19936850/nodejs-error-node-js810-var-cwd-process-cwd

The reason maybe following.
I have start http-server from ./dist directory, that was removed and created during grunt:clean task

I hope, that this helps somebody.
